os: linux
language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - python wikiraider.py list
  - python wikiraider.py parse -u 'https://dumps.wikimedia.org/kiwiki/20200401'